creatE user TEST_ACCOUNT
IDENTIFIED BY TIGER;

grant connect, resource to TEST_ACCOUNT;


GRANT SELECT ON SCOTT.EMP TO TEST_ACCOUNT; 
GRANT SELECT ON SCOTT.SALGRADE TO TEST_ACCOUNT; 
GRANT SELECT ON SCOTT.DEPT TO TEST_ACCOUNT; 

CREATE SYNONYM SEMP
FOR SCOTT.EMP;

CREATE SYNONYM SSALG
FOR SCOTT.SALGRADE;

CREATE SYNONYM SDEP
FOR SCOTT.DEPT;

DROP SYNONYM SSALG;

GRANT CREATE TABLE TO TEST_ACCOUNT;

 
GRANT SELECT,INSERT ON TEST_ACCOUNT.CUST TO SCOTT;